### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by ainkeri** [nuclearkittens/tsoha-grocery-list#1]
Review:
- Your instructions are clear and easy to understand, had no problems opening the project and testing it.
- Registration works, but (as you said in your README.md known issues) you can for example registrate with no numbers in username even though it's required in registration page.
- Otherwise all the functionalities you said would work are working: registration, log in and log out.
- Other pages work too, even though they don't have the functionality yet.
- As you said in your README.md again, the database is not implemented in the project. Otherwise I think you have specified your database tables smartly.
- With the code, you have divided it into different files (such as routes, users) cleverly and the repository looks neat.
- Good luck with the project! Even though you said it's ugly concentrate in the database and other functionality before, you can make it look prettier towards end :)

**Comment by nuclearkittens** [comment]
thanks for the feedback!
most of the errors should now be caught as intended, and the registration instructions have been clarified.
